const DATA = {
  experience: [
    {
      title: "Senior Mobile Developer",
      company: "One Studio",
      badges: ["Remote", "Full Time"],
      date: "Aug 2025 - Present",
      points: [
        "Lead mobile development initiatives in a fast-paced venture-building environment, collaborating closely with cross- functional teams to design, build, test, and scale new digital products.",
        "Drive architecture decisions and help transform early-stage ideas into market-ready mobile applications that support the studio's multiple startup ventures.",
        "Leverage Claude Code daily as an AI-augmented development tool for scaffolding, debugging, refactoring, and code review \u2014 significantly accelerating delivery velocity.",
        "Champion AI-first, spec-driven development, using structured specifications to guide implementation and ensure consistency across projects.",
        "Developed and maintained internal AI-friendly starter kits to standardize workflows and enhance team productivity.",
      ],
    },
    {
      title: "Mobile App Developer",
      company: "LoadServ",
      badges: ["On-site", "Full Time"],
      date: "March 2023 - Aug 2025",
      points: [
        "Engineered and deployed multiple production Flutter applications, managing the entire lifecycle from development to App Store/Play Store publication.",
        "Established robust DevOps workflows by implementing CI/CD pipelines using GitHub Actions, Codemagic, and Fastlane, reducing deployment time and enhancing release reliability.",
        "Mentored junior developers, conducted code reviews, and led technical interviews to recruit top talent and build a high-performing mobile engineering team.",
      ],
    },
    {
      title: "Flutter Developer",
      company: "Invasso LLC",
      badges: ["Remote", "Task Based"],
      date: "Jan 2025 - Present",
      points: [
        'Develop and maintain the "Bagels" ecosystem, a comprehensive restaurant management suite including an omnichannel POS system with offline capabilities.',
        "Modernize and optimize legacy codebases for User and Delivery applications, improving stability and performance while implementing new features for seamless order management.",
      ],
    },
  ],

  projects: [
    {
      name: "El-Dahan",
      category: "food",
      icon: "./assets/dahan.png",
      tag: "Food Delivery",
      desc: "A comprehensive food delivery app featuring a robust loyalty system and three-level nested product options. Built with offline capabilities using local storage and integrated with FCM for real-time tracking.",
      tech: ["Flutter", "Isar", "Paymob", "FCM"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.simpletouch.eldahan&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/el-dahan-%D8%A7%D9%84%D8%AF%D9%87%D8%A7%D9%86/id1546220454" },
      ],
    },
    {
      name: "ZOD - \u0645\u0632\u0627\u062F\u0627\u062A \u0627\u0644\u0633\u0639\u0648\u062F\u064A\u0629",
      category: "marketplace",
      icon: "./assets/zod.png",
      tag: "Auction",
      desc: "A real-time auction marketplace allowing users to bid using points. Powered by Socket.IO for instant updates and secured with PayTabs integration.",
      tech: ["Socket.IO", "PayTabs", "Real-time"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=app.zod.com" },
        { type: "apple", url: "https://apps.apple.com/eg/app/zod-%D9%85%D8%B2%D8%A7%D8%AF%D8%A7%D8%AA-%D8%A7%D9%84%D8%B3%D8%B9%D9%88%D8%AF%D9%8A%D8%A9/id6744919634" },
        { type: "web", url: "https://zod.shop/" },
      ],
    },
    {
      name: "Rydo",
      category: "ai",
      icon: "./assets/rydo.png",
      tag: "AI Travel",
      desc: "An AI-powered travel assistant for the UAE, leveraging OpenAI and Google Maps to generate personalized itineraries. Features a conversational chatbot and In-app purchases.",
      tech: ["OpenAI", "Google Maps", "RevenueCat"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=app.rydo.ae" },
        { type: "apple", url: "https://apps.apple.com/eg/app/rydo/id6745006103" },
        { type: "web", url: "https://rydo.ae/" },
      ],
    },
    {
      name: "Yazda",
      category: "entertainment",
      icon: "./assets/yazda.png",
      tag: "Trivia",
      desc: "A quiz-based competition app with scheduled knowledge challenges where outcomes are determined by answer accuracy and response speed. Features a seat-based entry system with transparent scoring and prize offerings.",
      tech: ["Flutter", "Real-time", "Competitions"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.yazda.app&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/yazda-app/id6758605595" },
        { type: "web", url: "https://yazda.pro/" },
      ],
    },
    {
      name: "Athoob",
      category: "food",
      icon: "./assets/athoob.jpg",
      tag: "Delivery",
      desc: "Delivery application with precise location validation and custom map markers. Integrated with Moyasar for payments and Isar for efficient local cart storage.",
      tech: ["Google Maps", "Moyasar", "Isar"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.loadserv.athoob&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/%D8%B9%D8%B0%D9%88%D8%A8/id6475668808" },
      ],
    },
    {
      name: "Sawa",
      category: "marketplace",
      icon: "./assets/sawa.png",
      tag: "Real Estate",
      desc: "A specialized real estate management platform offering advanced search and filtering. Includes distinct roles for users and admins with strict permission guards.",
      tech: ["RBAC", "Deep Links", "Search"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.realestate.sawa&pcampaignid=web_share" },
        { type: "github", url: "https://github.com/RoberRaf/sawa_preview/blob/main/README.md" },
      ],
    },
    {
      name: "Fakker Game",
      category: "entertainment",
      icon: "./assets/fakkar.png",
      tag: "Game",
      desc: "Competitive triva game. Team vs Team. In-app package purchases.",
      tech: ["Game Logic", "IAP"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.fakker.fakker&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/fakker/id6745900254" },
        { type: "github", url: "https://github.com/RoberRaf/Fakker_preview/blob/main/README.md" },
      ],
    },
    {
      name: "Homzready",
      category: "health-social",
      icon: "./assets/homz.jpg",
      tag: "Social",
      desc: "Dynamic service engagement platform connecting providers and seekers. Equipped with social login, media-rich chat, and PDF viewing capabilities.",
      tech: ["Chat", "Social Auth", "Media"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.alameldin.homzready&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/homzready/id6451056403" },
      ],
    },
    {
      name: "Kure",
      category: "health-social",
      icon: "./assets/kure.png",
      tag: "Medical",
      desc: "Telemedicine application facilitating online consultations with certified dermatologists. Features video calling, screen sharing, and E-signed prescriptions.",
      tech: ["Video Call", "WebRTC", "Deep Links"],
      links: [{ type: "pending" }],
    },
    {
      name: "Tizkar",
      category: "marketplace",
      icon: "./assets/tizkar.png",
      tag: "E-commerce",
      desc: "Single-seller souvenir shop for tourists. Support ordering from abroad with multi-currency features and fair delivery cost estimation.",
      tech: ["Localization", "Maps", "Auth"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.app.tizkar&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/tizkar-souvenirs-gifts/id6452839163?platform=iphone" },
      ],
    },
    {
      name: "Pupila",
      category: "entertainment",
      icon: "./assets/pupila.png",
      tag: "Kids",
      desc: "Interactive educational app for kids offering pictured books, video narration, and quizzes. Built with offline capabilities and secure subscription management.",
      tech: ["SQLite", "Offline", "RevenueCat"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.pupila.pupila&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/us/app/pupila-kids-childrens-books/id6444745083" },
      ],
    },
    {
      name: "Tabali",
      category: "food",
      icon: "./assets/tabali.png",
      tag: "Food",
      desc: "Smart food ordering app that dynamically adjusts pricing based on location and nearest branch. Features a responsive local cart ensuring real-time accuracy.",
      tech: ["Maps", "Dynamic Pricing", "Real-time Cart"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.loadserv.tabalibistro&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/eg/app/tabali-bistro/id6740022945" },
      ],
    },
    {
      name: "Hive Manager (\u0627\u062F\u0627\u0631\u0629 \u0627\u0644\u0645\u0646\u062D\u0644)",
      category: "business",
      icon: "./assets/hive.png",
      tag: "Management",
      desc: "A freelance application helping in managing hives and apiaries. Features in-app graphs, statistics tables, Open Street Maps, and task management with scheduled notifications.",
      tech: ["Graphs", "OSM", "Notifications"],
      links: [
        { type: "demo", url: "https://drive.google.com/file/d/1zgVtGd-cTCQFk6EPNukYKhii-ONT3bmH/view" },
      ],
    },
    {
      name: "BookCast",
      category: "entertainment",
      icon: "./assets/bookcast.png",
      tag: "Audio",
      desc: "Feature-rich audiobook streaming service with background playback and offline downloads. Offers plans managed through RevenueCat.",
      tech: ["Audio Service", "Offline", "RevenueCat"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.ibookcast.ibook&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/us/app/bookcast-audiobooks-stories/id1583479714" },
      ],
    },
    {
      name: "Menu Egypt",
      category: "food",
      icon: "./assets/menue_egypt.png",
      tag: "Utility",
      desc: "Comprehensive restaurant guide allowing users to discover menus and order online from a vast directory of local eateries.",
      tech: ["Directory", "Ordering"],
      links: [
        { type: "play", url: "https://play.google.com/store/apps/details?id=com.menuegypt.menuegupt&pcampaignid=web_share" },
        { type: "apple", url: "https://apps.apple.com/cz/app/menu-egypt/id1630657799" },
      ],
    },
    {
      name: "Growth",
      category: "business",
      icon: "./assets/growth.png",
      tag: "Enterprise",
      desc: "Internal enterprise tool with role-based access. Features image and video galleries with thumbnail generation for media management.",
      tech: ["Media", "Enterprise"],
      links: [
        { type: "demo", url: "https://drive.google.com/file/d/1zgVtGd-cTCQFk6EPNukYKhii-ONT3bmH/view" },
      ],
    },
    {
      name: "Cloud Kitchen",
      category: "food",
      icon: "./assets/cloud_kitchen.png",
      tag: "Food",
      desc: "Features background location service, order tracking video streaming, rewarding system, and support chat.",
      tech: ["Paymob", "Streaming", "Location"],
      links: [
        { type: "apple", url: "https://apps.apple.com/eg/app/cloud-kitchen/id6689521269" },
      ],
    },
  ],

  skills: [
    {
      title: "Mobile Development Stack",
      tags: [
        "Flutter & Dart",
        "Socket.IO & WebSockets",
        "WebRTC & Streaming",
        "Offline-first Architecture",
        "OpenAI API Integration",
        "Background Services",
        "Isar DB & SQLite",
        "Payment Gateways (Paymob/Moyasar/PayTabs)",
        "Google Maps & OSM",
        "RevenueCat & IAP",
        "FCM & Notifications",
      ],
    },
    {
      title: "Tools & Methodologies",
      tags: [
        "Clean Architecture & SOLID",
        "CI/CD (Codemagic, GitHub Actions, Fastlane)",
        "Shorebird & CodePush",
        "Unit & Widget Testing",
        "Version Control",
        "Agile/Scrum",
        "MacOS & Xcode",
        "Linux & Bash Scripting",
        "Figma & UI/UX",
      ],
    },
    {
      title: "AI-Augmented Development",
      tags: [
        "Claude Code (Daily Driver)",
        "AI-first Spec-driven Development",
        "Agentic AI skills",
        "AI-friendly Starter Kits",
        "Context management",
        "System Prompt Design",
        "AI Output Evaluation",
      ],
    },
    {
      title: "Web Development Stack",
      tags: [
        "PHP & Laravel",
        "MySQL",
        "RESTful APIs",
        "JS/TS",
        "Tailwind",
        "HTML5 & CSS3",
        "Angular",
      ],
    },
  ],

  courses: [
    {
      title: "ITI Intensive Code Camp - PHP Full Stack",
      subtitle: "Information Technology Institute \u2022 August 2024",
      certificates: [
        { url: "https://raw.githubusercontent.com/RoberRaf/Certificates/refs/heads/main/ITI-PHP.jpg" },
      ],
    },
    {
      title: "Flutter & Dart - The Complete Guide",
      subtitle: "Maximilian Schwarzmuller \u2022 Udemy 2023",
      certificates: [{ url: "./certificates/Flutter.pdf" }],
    },
    {
      title: "CS50: Introduction to Computer Science",
      subtitle: "Harvard University \u2022 Professor David J. Malan",
      certificates: [{ noLink: true }],
    },
    {
      title: "Algorithms and Data Structure Decoding",
      subtitle: "Ahmed Metwally (Metwally Labs)",
      certificates: [
        { url: "https://raw.githubusercontent.com/RoberRaf/portfolio/main/assets/rober-Algorithms-Analysis-and-Design.png" },
        { url: "https://raw.githubusercontent.com/RoberRaf/portfolio/main/assets/rober-Data-Structures-Decode.png" },
      ],
    },
    {
      title: "Mahara-Tech Courses",
      tags: [
        { label: "Kotlin", url: "./certificates/Kotlin_crtf.pdf" },
        { label: "Linux", url: "./certificates/ubuntu.pdf" },
        { label: "Database", url: "./certificates/Db_fundamentals.pdf" },
        { label: "PHP", url: "./certificates/PHP&MySql.pdf" },
        { label: "TypeScript", url: "./certificates/type_script.pdf" },
        { label: "Freelancing", url: "./certificates/freelancing.pdf" },
      ],
    },
  ],

  filterCategories: [
    { key: "all", label: "All" },
    { key: "food", label: "Food & Delivery" },
    { key: "marketplace", label: "Marketplace" },
    { key: "entertainment", label: "Entertainment" },
    { key: "health-social", label: "Health & Social" },
    { key: "business", label: "Business" },
    { key: "ai", label: "AI" },
  ],

  stats: [
    { target: 18, label: "Apps Published", delayClass: "" },
    { target: 4, label: "Years Experience", delayClass: "reveal-delay-1" },
    { target: 5, label: "Countries Served", delayClass: "reveal-delay-3" },
  ],

  contact: {
    phone: "+201285566439",
    email: "roberselwanes@gmail.com",
    linkedin: "https://www.linkedin.com/in/rober-boules-906a18188/",
    github: "https://github.com/RoberRaf",
  },
};
